server.port=8080
spring.datasource.url=jdbc:mariadb://10.100.247.78:3306/student_db
spring.datasource.username=root
spring.datasource.password=Redhat123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
